name: Deploy Docker a Elastic Beanstalk

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B clean package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}yttgg67y

      - name: Generate docker-compose.yml
        run: |
          echo "services:" > docker-compose.yml
          echo "  app:" >> docker-compose.yml
          echo "    image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}" >> docker-compose.yml
          echo "    ports:" >> docker-compose.yml
          echo "      - '80:8080'" >> docker-compose.yml
          echo "    restart: always" >> docker-compose.yml

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1
          application_name: HogwartsAPI
          environment_name: HogwartsAPI-env
          version_label: hogwarts-${{ github.run_number }}
          deployment_package: docker-compose.yml